### ISSUE TITLE
get error Token not available in request. Please specify a valid token as HTTP header.

### ISSUE THREAD

**Issue by 123bistami** [hendt/ebay-api#123]
my code 

```
const eBay = new eBayApi({
        appId: 'XXXXXXXXXXXXXXXXXX',
        certId: 'XXXXXXXXXXXXXXXXXX',
        devId: 'XXXXXXXXXXXXXXXXXX',
        authToken: 'XXXXXXXXXXXXXXXXXX',
        siteId: eBayApi.SiteId.EBAY_DE,
        marketplaceId: eBayApi.MarketplaceId.EBAY_DE,
        sandbox: false
    });

(async () => {
        const result = await eBay.shopping.GetUserProfile({
            UserID: 'xxxxx',
            IncludeSelector: 'Details'
        });

        console.log(result);
    })()

console.log(item)
```

response is

```
description: 'Token not available in request. Please specify a valid token as HTTP header.',
  meta: {
    Timestamp: '2022-08-14T12:08:53.414Z',
    Ack: 'Failure',
    Errors: {
      ShortMessage: 'Token not available in request.',
      LongMessage: 'Token not available in request. Please specify a valid token as HTTP header.',
      ErrorCode: 1.33,
      SeverityCode: 'Error',
      ErrorClassification: 'RequestError'
    },
    Build: 'E1199_CORE_APILW_19146596_R1',
    Version: 1199,
    [Symbol(raw-error)]: {
      Timestamp: '2022-08-14T12:08:53.414Z',
      Ack: 'Failure',
      Errors: {
        ShortMessage: 'Token not available in request.',
        LongMessage: 'Token not available in request. Please specify a valid token as HTTP header.',
        ErrorCode: 1.33,
        SeverityCode: 'Error',
        ErrorClassification: 'RequestError'
      },
      Build: 'E1199_CORE_APILW_19146596_R1',
      Version: 1199
    }
  }
}
```
i had inserted a static token, ebay API explorer call works fine, pls help!

**Comment by dantio** [comment]
`authToken` is used for the traditional Auth'N'Auth method.
I think you are looking for: 
```
eBay.OAuth2.setCredentials('XXXXXXXXXXXXXXXXXX');
// This token can be seen in the eBay API explorer.
```

**Comment by 123bistami** [comment]
same error

my code 

```
const eBay = new eBayApi({
        appId: 'XXXXXXXXXXXXXXXXXX',
        certId: 'XXXXXXXXXXXXXXXXXX',
        devId: 'XXXXXXXXXXXXXXXXXX',
        authToken: 'XXXXXXXXXXXXXXXXXX',
        siteId: eBayApi.SiteId.EBAY_DE,
        marketplaceId: eBayApi.MarketplaceId.EBAY_DE,
        sandbox: false
    });


(async () => {
        const result = await eBay.shopping.GetUserProfile({
            UserID: 'xxxxx',
            IncludeSelector: 'Details'
        });

        console.log(result);
    })()
```

response is

```
description: 'Token not available in request. Please specify a valid token as HTTP header.',
  meta: {
    Timestamp: '2022-08-14T12:08:53.414Z',
    Ack: 'Failure',
    Errors: {
      ShortMessage: 'Token not available in request.',
      LongMessage: 'Token not available in request. Please specify a valid token as HTTP header.',
      ErrorCode: 1.33,
      SeverityCode: 'Error',
      ErrorClassification: 'RequestError'
    },
    Build: 'E1199_CORE_APILW_19146596_R1',
    Version: 1199,
    [Symbol(raw-error)]: {
      Timestamp: '2022-08-14T12:08:53.414Z',
      Ack: 'Failure',
      Errors: {
        ShortMessage: 'Token not available in request.',
        LongMessage: 'Token not available in request. Please specify a valid token as HTTP header.',
        ErrorCode: 1.33,
        SeverityCode: 'Error',
        ErrorClassification: 'RequestError'
      },
      Build: 'E1199_CORE_APILW_19146596_R1',
      Version: 1199
    }
  }
}
```
i had inserted a static token, ebay API explorer call works fine, pls help!

**Comment by 123bistami** [comment]
> same error
> 
> my code
> 
> ```
> const eBay = new eBayApi({
>         appId: 'XXXXXXXXXXXXXXXXXX',
>         certId: 'XXXXXXXXXXXXXXXXXX',
>         devId: 'XXXXXXXXXXXXXXXXXX',
>         siteId: eBayApi.SiteId.EBAY_DE,
>         marketplaceId: eBayApi.MarketplaceId.EBAY_DE,
>         sandbox: false
>     });
> 
> eBay.OAuth2.setCredentials('XXXXXXXXXXXXXXXXXX');
> 
> 
> (async () => {
>         const result = await eBay.shopping.GetUserProfile({
>             UserID: 'xxxxx',
>             IncludeSelector: 'Details'
>         });
> 
>         console.log(result);
>     })()
> ```
> 
> response is
> 
> ```
> description: 'Token not available in request. Please specify a valid token as HTTP header.',
>   meta: {
>     Timestamp: '2022-08-14T12:08:53.414Z',
>     Ack: 'Failure',
>     Errors: {
>       ShortMessage: 'Token not available in request.',
>       LongMessage: 'Token not available in request. Please specify a valid token as HTTP header.',
>       ErrorCode: 1.33,
>       SeverityCode: 'Error',
>       ErrorClassification: 'RequestError'
>     },
>     Build: 'E1199_CORE_APILW_19146596_R1',
>     Version: 1199,
>     [Symbol(raw-error)]: {
>       Timestamp: '2022-08-14T12:08:53.414Z',
>       Ack: 'Failure',
>       Errors: {
>         ShortMessage: 'Token not available in request.',
>         LongMessage: 'Token not available in request. Please specify a valid token as HTTP header.',
>         ErrorCode: 1.33,
>         SeverityCode: 'Error',
>         ErrorClassification: 'RequestError'
>       },
>       Build: 'E1199_CORE_APILW_19146596_R1',
>       Version: 1199
>     }
>   }
> }
> ```
> 
> i had inserted a static token, ebay API explorer call works fine, pls help!

i fixed it thanks

**Comment by dantio** [comment]
what was the issue?

**Comment by 123bistami** [comment]
Hello,

i set the token from api explorer, the service i will use is shopping API/ GetMultipleItems after about 1 hour i get token invalid error.

I think the api explorer token expires in ~ 1 hour, but the token in the user keys section expires in 2 yours an it is shorter then the explorer api token.

Why ebays api makes live so difficult, can you help me. I will use the API for my private service, i have no wensite and endpoint URL.

**Comment by 123bistami** [comment]
Thank you for your tips. I have to use untraditional API i will check multiple items if they are in stock, this is only possible at shopping api or browse api. Do you habe an idea how can i get the token with this app without redirect url. Can i receive first token with postman and then refresh it with this app or do i have to sign again if i will refresh it. I have no redirect url i will use the api for my private things.

**Comment by 123bistami** [comment]
Browse API search ignoring aspect filter

`aspect_filter=categoryId:XXXX,BRAND:{Microsoft}`

No error in response but ignoring, do you have an idea?

**Comment by dantio** [comment]
Show me the whole code. Does it work with ebay api explorer? Did you managed to obtain the access token?

**Comment by 123bistami** [comment]
> For example:
> 
> `https://api.ebay.com/buy/browse/v1/item_summary/search?category_ids=9355&limit=3&filter=sellers:{alba_mobil}&aspect_filter=categoryId=9355,Brand:{Apple},Model:{Apple iPhone 13 Pro}`
> 
> API Explorer Ignoring Aspect Filter, response contains no aspect filter errors. I want to filter items brand and model, can you help me. ![CC4AD969-9F7A-43EB-B1CE-A0E2842B014F](https://user-images.githubusercontent.com/28767886/185220039-b69e4a4d-b12b-4797-88e2-f37dfd4db2f3.jpeg)

Any idea?

**Comment by dantio** [comment]
You have to replace `categoryId=9355` with `categoryId:9355` in `aspect_filter` like this:
`https://api.ebay.com/buy/browse/v1/item_summary/search?category_ids=9355&limit=3&filter=sellers:{alba_mobil}&aspect_filter=categoryId:9355,Brand:{Apple},Model:{Apple iPhone 13 Pro}`

```js
await eBay.browse.search({
  "category_ids": "9355",
  "limit": 3,
  "filter": "sellers:{alba_mobil}",
  "aspect_filter": "categoryId:9355,Brand:{Apple},Model:{Apple iPhone 13 Pro}"
})
```

**Comment by 123bistami** [comment]
Not working

for example:

`https://api.ebay.com/buy/browse/v1/item_summary/search?category_ids=139971&limit=3&filter=sellers:{saturn}&aspect_filter=categoryId:139971,Brand:{Microsoft},Model:{Microsoft Xbox Series X}`

Reponse included brand nintendo.

**Comment by 123bistami** [comment]
> Not working
> 
> for example:
> 
> `https://api.ebay.com/buy/browse/v1/item_summary/search?category_ids=139971&limit=3&filter=sellers:{saturn}&aspect_filter=categoryId:139971,Brand:{Microsoft},Model:{Microsoft Xbox Series X}`
> 
> Reponse included brand nintendo.

Any idea, why the api is ignoring aspect filter.

**Comment by dantio** [comment]
Can you try with encoded aspect_filter?
`https://api.ebay.com/buy/browse/v1/item_summary/search?category_ids=139971&limit=3&filter=sellers:{saturn}&aspect_filter=categoryId%3A139971%2CBrand%3A%7BMicrosoft%7D%2CModel%3A%7BMicrosoft%20Xbox%20Series%20X%7D`

Maybe you should ask in eBay Developer Forum...

**Comment by nrathi** [comment]
I think this might be related.

I'm calling "getMultipleItems" from the Shopping API:

`eBayApi.shopping.GetMultipleItems.(fields, { useIaf: true });`

When my OAuth2 token is expired, I get this error message:

```
EbayApiError: Invalid token.
    at checkEBayResponse (/Users/neha/superset/node_modules/.pnpm/ebay-api@8.4.1/node_modules/ebay-api/lib/errors/index.js:206:15)
    at XMLRequest.request (/Users/neha/superset/node_modules/.pnpm/ebay-api@8.4.1/node_modules/ebay-api/lib/api/traditional/XMLRequest.js:163:46)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Traditional.request (/Users/neha/superset/node_modules/.pnpm/ebay-api@8.4.1/node_modules/ebay-api/lib/api/traditional/index.js:183:20)
  description: 'Invalid token. Please specify a valid token as HTTP header.',
  meta: {
    Timestamp: '2023-09-21T17:22:49.013Z',
    Ack: 'Failure',
    Errors: {
      ShortMessage: 'Invalid token.',
      LongMessage: 'Invalid token. Please specify a valid token as HTTP header.',
      ErrorCode: 1.32,
      SeverityCode: 'Error',
      ErrorClassification: 'RequestError'
    },
    Build: '1299_CORE_APILW_19146596_R1',
    Version: 1299,
    [Symbol(raw-error)]: {
      Timestamp: '2023-09-21T17:22:49.013Z',
      Ack: 'Failure',
      Errors: [Object],
      Build: '1299_CORE_APILW_19146596_R1',
      Version: 1299
    }
  }
}
```

And unfortunately, this isn't caught by the `autoRefreshToken` logic: https://github.com/hendt/ebay-api/blob/932d6878269ce3eae3a0457d2842ad9f293dc5b6/src/api/traditional/index.ts#L152

The above logic seems to correctly handle errors for the Trading API, but not the Shopping API.

**Comment by nrathi** [comment]
I think this might be related.

I'm calling "getMultipleItems" from the Shopping API:

`eBayApi.shopping.GetMultipleItems.(fields, { useIaf: true });`

When my OAuth2 token is expired, I get this error message:

```
EbayApiError: Invalid token.
  description: 'Invalid token. Please specify a valid token as HTTP header.',
  meta: {
    Timestamp: '2023-09-21T17:22:49.013Z',
    Ack: 'Failure',
    Errors: {
      ShortMessage: 'Invalid token.',
      LongMessage: 'Invalid token. Please specify a valid token as HTTP header.',
      ErrorCode: 1.32,
      SeverityCode: 'Error',
      ErrorClassification: 'RequestError'
    },
    Build: '1299_CORE_APILW_19146596_R1',
    Version: 1299,
    [Symbol(raw-error)]: {
      Timestamp: '2023-09-21T17:22:49.013Z',
      Ack: 'Failure',
      Errors: [Object],
      Build: '1299_CORE_APILW_19146596_R1',
      Version: 1299
    }
  }
}
```

And unfortunately, this isn't caught by the `autoRefreshToken` logic: https://github.com/hendt/ebay-api/blob/932d6878269ce3eae3a0457d2842ad9f293dc5b6/src/api/traditional/index.ts#L152

The above logic seems to correctly handle errors for the Trading API, but not the Shopping API.

**Comment by dantio** [comment]
Thank you for reporting it and including the error message! I'll fix it soon.

**Comment by nrathi** [comment]
Can you re-open this ticket?

**Comment by dantio** [comment]
Fix release in `v8.5.1`
