### ISSUE TITLE
Inventory API > bulkMigrateListings call - Invalid value for header Accept-Language.

### ISSUE THREAD

**Issue by doverradio** [hendt/ebay-api#137]
Hello,

I am getting stuck on the bulkMigrateListings call in the Inventory API.  I constantly receive this error and I have no idea how to set this value.  

The error is `Invalid value for header Accept-Language.`

Here is my code to make the call (I am using version 6.0.1 of your library btw):
```
exports.bulkMigrateListing = async (req, res) =>
{ 
  let a = {}
  let { user, listingIds } = req.body
  a.user = user
  await handleAuthToken( user ) // separately, this handles OAuth prior to making this call
  try {
    let body = {
      requests: listingIds  // contains payload of ItemIDs
    }
    a.result = await eBay.sell.inventory.bulkMigrateListing(body)
    res.json( a.result )
  } catch (e) {
    console.log(`bulkMigrateListing e: `, e)
    res.status(400).json( { error: e } )
  }
}
```

The full error:
```
{'error': {'message': 'Invalid value for header Accept-Language.',
  'description': 'Bad Request',
  'stack': 'EBayError: Invalid value for header Accept-Language.\n    at handleEBayError (C:\\Users\\project\\backend\\node_modules\\ebay-api\\lib\\errors\\index.js:186:11)\n    at Inventory.request (C:\\Users\\project\\backend\\node_modules\\ebay-api\\lib\\api\\restful\\index.js:167:42)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async Inventory.doRequest (C:\\Users\\project\\backend\\node_modules\\ebay-api\\lib\\api\\restful\\index.js:128:20)\n    at async exports.bulkMigrateListing (C:\\Users\\project\\backend\\controllers\\ebay.js:4983:16)',
  'type': 'EBayError',
  'meta': {'errorId': 25709,
   'domain': 'API_INVENTORY',
   'subdomain': 'Selling',
   'category': 'REQUEST',
   'message': 'Invalid value for header Accept-Language.',
   'res': {'status': 400,
    'statusText': 'Bad Request',
    'headers': {'x-ebay-c-request-id': 'ri=...',
     'rlogid': '...',
     'x-ebay-c-version': '1.0.0',
     'x-ebay-client-tls-version': 'TLSv1.3',
     'set-cookie': ['ebay=...;Domain=.ebay.com;Path=/; Secure'],
     'content-type': 'application/json',
     'date': 'Wed, 04 Jan 2023 04:40:02 GMT',
     'server': 'ebay-proxy-server',
     'x-envoy-upstream-service-time': '38',
     'x-ebay-pop-id': 'UFES2-RNOAZ03-api',
     'connection': 'close',
     'transfer-encoding': 'chunked'},
    'data': {'errors': [{'errorId': 25709,
       'domain': 'API_INVENTORY',
       'subdomain': 'Selling',
       'category': 'REQUEST',
       'message': 'Invalid value for header Accept-Language.'}]}},
   'req': {'url': 'https://api.ebay.com/sell/inventory/v1/bulk_migrate_listing',
    'method': 'post',
    'headers': {'Accept': 'application/json, text/plain, */*',
     'Content-Type': 'application/json',
     'Access-Control-Allow-Origin': '*',
     'Access-Control-Allow-Headers': 'X-Requested-With, Origin, Content-Type, X-Auth-Token',
     'Access-Control-Allow-Methods': 'GET, PUT, POST, DELETE',
     'Cache-Control': 'no-cache',
     'Accept-Encoding': 'application/gzip',
     'X-EBAY-C-MARKETPLACE-ID': 'EBAY_US',
     'Accept-Language': 'en_US',
     'Content-Language': 'en_US',
     'Authorization': 'Bearer v^...=',
     'User-Agent': 'axios/0.21.4',
     'Content-Length': 284}}}}}
```

How to solve this?

**Comment by doverradio** [comment]
Solved the problem.  After digging through past issues, I came across one which mentioned how to set such headers.  After changing my code to the below code, it successfully made this call:

```
exports.bulkMigrateListing = async (req, res) => // https://developer.ebay.com/api-docs/sell/inventory/resources/inventory_item/methods/bulkMigrateListing
{ 
  let a = {}
  let { user, listingIds } = req.body
  a.user = user
  await handleAuthToken( user )
  try {
    let body = {
      requests: listingIds
    }
    eBay.req.instance.interceptors.request.use((request) => {
      request.headers['Accept-Language'] = 'en-US';
      request.headers['Content-Language'] = 'en-US';
      return request;
    })
    a.result = await eBay.sell.inventory.bulkMigrateListing(body)
    console.log(`Got a result...`, a.result)
    res.json( a.result )
  } catch (e) {
    console.log(`bulkMigrateListing e: `, e)
    res.status(400).json( { error: e } )
  }
}
```
