### ISSUE TITLE
GetSellerDashboard constantly returns error

### ISSUE THREAD

**Issue by doverradio** [hendt/ebay-api#146]
My code:
```
// https://developer.ebay.com/Devzone/XML/docs/Reference/eBay/GetSellerDashboard.html
exports.getSellerDashboard = async (req, res) => 
        { 
          let { user } = req.body
          await handleAuthToken( user )
          try 
          {
            let result = await eBay.trading.GetSellerDashboard()
            console.log(`Got a result...`, result)
            res.json( result )
          } catch (e) {
            console.log(`Got an error in getSellerDashboard...`, JSON.stringify( e, null, 4 ) )
            res.status(400).json( { error: e } )
          }
        }
```

The error:
```
{"error":{"message":"You are not eligible to access seller dashboard","description":"You are not eligible to access seller dashboard","stack":"EbayApiError: You are not eligible to access seller dashboard\n    at checkEBayResponse (C:\\Users\\User\\Desktop\\ backend\\node_modules\\ebay-api\\lib\\errors\\index.js:201:15)\n    at XMLRequest.request (C:\\Users\\User\\Desktop\\backend\\node_modules\\ebay-api\\lib\\api\\traditional\\XMLRequest.js:161:46)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async Traditional.request (C:\\Users\\User\\Desktop\\ backend\\node_modules\\ebay-api\\lib\\api\\traditional\\index.js:181:20)\n    at async Object.GetSellerDashboard (C:\\Users\\User\\Desktop\\backend\\node_modules\\ebay-api\\lib\\api\\traditional\\index.js:47:24)\n    at async exports.getSellerDashboard (C:\\Users\\User\\Desktop\\backend\\controllers\\ebay.js:14913:24)","type":"EbayApiError","meta":{"Timestamp":"2023-04-16T20:10:11.126Z","Ack":"Failure","Errors":{"ShortMessage":"You are not eligible to access seller dashboard","LongMessage":"You are not eligible to access seller dashboard","ErrorCode":21916055,"SeverityCode":"Error","ErrorClassification":"RequestError"},"Version":1271,"Build":"E1271_CORE_APISELLING_19187371_R1"}}}
```

Am I supposed to be passing in additional params?

**Comment by dantio** [comment]
From the Docs:
`To be eligible to view a Seller Dashboard, the user needs 10 or more Detailed Seller Ratings (across any of the four rating categories) within the last 12 months. If the user is not eligible, the call returns an error. Use GetFeedback to check the user's Detailed Seller Ratings (DSR).`

If you think you are eligible to view the Seller Dashboard you should get in contact with eBay.
