### ISSUE TITLE
Access token is not being refreshed by 403s on inventory item endpoint

### ISSUE THREAD

**Issue by K3vChan** [hendt/ebay-api#148]
* [X] Are you running the latest version?
* [X] Have you included sample input, output, error, and expected output? 
* [X] Have you checked if you are using correct configuration?

**Describe the bug**
I'm getting an access error from ebay when hitting the `https://api.ebay.com/sell/inventory/v1/inventory_item` endpoint when my token expires after the standard token expiration time according to the debug logs from this lib. `shouldRefreshToken` does not cover this, but does have an exception for a 401 here https://github.com/hendt/ebay-api/blob/d6d165e176b34bc444b4e7c37fdc0d9ca01927c9/src/api/restful/index.ts#L221, so I assume that not all api's are consistent with errors being returned. I did play with an expired token to try to get the correct error to be thrown by eBay by deleting a few characters off my token and that did result in a case where my token would have been refreshed. 

error - `{"errors":[{"errorId":1100,"domain":"ACCESS","category":"REQUEST","message":"Access denied","longMessage":"Insufficient permissions to fulfill the request."}]}`

the error clears when I manually refresh the tokens

### Code
```js
const getInventoryItems = (req, res) => {
ebayClient.OAuth2.setCredentials(oauth_token);
const items = await ebayClient.sell.inventory.getInventoryItems();
res.json({result: items})
}
```

### Output
```
2023-05-25T12:39:53.828Z ebay:error handleEBayError AxiosError: Request failed with status code 403
--
at settle (/app/web/node_modules/ebay-api/node_modules/axios/dist/node/axios.cjs:1898:12)
at Unzip.handleStreamEnd (/app/web/node_modules/ebay-api/node_modules/axios/dist/node/axios.cjs:2950:11)
at Unzip.emit (events.js:412:35)
at Unzip.emit (domain.js:537:15)
at endReadableNT (internal/streams/readable.js:1333:12)
at processTicksAndRejections (internal/process/task_queues.js:82:21) {
code: 'ERR_BAD_REQUEST',
config: {
transitional: {
silentJSONParsing: true,
forcedJSONParsing: true,
clarifyTimeoutError: false
},
adapter: [ 'xhr', 'http' ],
transformRequest: [ [Function: transformRequest] ],
transformResponse: [ [Function: transformResponse] ],
timeout: 0,
xsrfCookieName: 'XSRF-TOKEN',
xsrfHeaderName: 'X-XSRF-TOKEN',
maxContentLength: -1,
maxBodyLength: -1,
env: { FormData: [Function], Blob: null },
validateStatus: [Function: validateStatus],
headers: AxiosHeaders {
Accept: 'application/json, text/plain, */*',
'Access-Control-Allow-Origin': '*',
'Access-Control-Allow-Headers': 'X-Requested-With, Origin, Content-Type, X-Auth-Token',
'Access-Control-Allow-Methods': 'GET, PUT, POST, DELETE',
'Content-Type': 'application/json',
'Cache-Control': 'no-cache',
'Accept-Encoding': 'application/gzip',
'X-EBAY-C-MARKETPLACE-ID': 'EBAY_US',
'Accept-Language': 'en-US',
'Content-Language': 'en-US',
Authorization: 'Bearer REDACTED',
'User-Agent': 'axios/1.3.5'
},
params: { limit: undefined, offset: undefined },
method: 'get',
url: 'https://api.ebay.com/sell/inventory/v1/inventory_item',
data: undefined
}
```

### expected data
a list of inventory items. 

```
{"total":1,"size":1,"href":"/sell/inventory/v1/inventory_item?offset=0&limit=25","limit":25,"inventoryItems":[{"sku":"camisausada1","locale":"en_US","product":{"title":"Camisa usada 01","aspects":{"Brand":["Casual"],"Size Type":["Regular"],"Type":["T-Shirt"],"Department":["Men"],"Size":["S"],"Color":["White"]},"imageUrls":["https://i.ebayimg.com/00/s/ODAwWDgwMA==/z/89gAAOSwHcJkbuuY/$_3.PNG"]},"condition":"NEW_OTHER","packageWeightAndSize":{"dimensions":{"width":2,"length":2,"height":2,"unit":"INCH"},"weight":{"value":1,"unit":"POUND"}},"availability":{"shipToLocationAvailability":{"quantity":1}}}]}
```

**Would you like to work on this issue?**
- [X] Yes
- [ ] No
- [ ] Maybe

**Comment by dantio** [comment]
v8.4.1 released
