### ISSUE TITLE
description: 'There was a problem with an eBay internal system or process. Contact eBay developer support for assistance',

### ISSUE THREAD

**Issue by sughramehdi-swagkicks** [hendt/ebay-api#157]
**Code - Express JS**

```
try {
    eBay.req.instance.interceptors.request.use((request) => {
      request.headers['Accept'] = 'application/json';
      request.headers['Content-Type'] = 'application/json';
      request.headers['Content-Type'] = 'application/x-www-form-urlencoded';
      request.headers['Accept-Language'] = 'en-US';
      request.headers['Content-Language'] = 'en-US';
      return request;
    });
    const resID = await eBay.sell.inventory.createOrReplaceInventoryItem(
      SKU,
      InventoryItem
    );
    console.log(resID);
```
**Input**

```
SKU -> SK-568
InventoryItem -> {
product: {
title: 'title',
 description: 'desc',
 imageUrls: [
 'https://i.ebayimg.com/00/s/Mjc2WDE2MDA=/z/X-EAAOSwJU9lXa0W/$_1.PNG?set_id=2'  ],
 aspects: {
   Brand: [Array],
  Color: [Array],
'Bottle Material': [Array],
   'Country/Region of Manufacture': [Array],
    'Unit Type': [Array]
  }
  },
 condition: 'USED_GOOD',
  availability: { shipToLocationAvailability: { quantity: 1 } }
}
```

**Error**

```
EBayAccessDenied: Internal error
2023-11-22T07:26:31.704492+00:00 app[web.1]:     at handleEBayError (/app/node_modules/ebay-api/lib/errors/index.js:157:15)
2023-11-22T07:26:31.704493+00:00 app[web.1]:     at Inventory.request (/app/node_modules/ebay-api/lib/api/restful/index.js:161:44)
2023-11-22T07:26:31.704501+00:00 app[web.1]:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-11-22T07:26:31.704501+00:00 app[web.1]:     at async Inventory.doRequest (/app/node_modules/ebay-api/lib/api/restful/index.js:125:24)
2023-11-22T07:26:31.704501+00:00 app[web.1]:     at async /app/app.js:239:19 {
2023-11-22T07:26:31.704502+00:00 app[web.1]:   description: 'There was a problem with an eBay internal system or process. Contact eBay developer support for assistance',
2023-11-22T07:26:31.704503+00:00 app[web.1]:   meta: {
2023-11-22T07:26:31.704503+00:00 app[web.1]:     errorId: 2003,
2023-11-22T07:26:31.704503+00:00 app[web.1]:     domain: 'ACCESS',
2023-11-22T07:26:31.704504+00:00 app[web.1]:     category: 'APPLICATION',
2023-11-22T07:26:31.704505+00:00 app[web.1]:     message: 'Internal error',
2023-11-22T07:26:31.704505+00:00 app[web.1]:     longMessage: 'There was a problem with an eBay internal system or process. Contact eBay developer support for assistance',
2023-11-22T07:26:31.704505+00:00 app[web.1]:     parameters: [ [Object] ],
2023-11-22T07:26:31.704506+00:00 app[web.1]:     res: {
2023-11-22T07:26:31.704506+00:00 app[web.1]:       status: 500,
2023-11-22T07:26:31.704506+00:00 app[web.1]:       statusText: 'Internal Server Error',
2023-11-22T07:26:31.704507+00:00 app[web.1]:       headers: [Object [AxiosHeaders]],
2023-11-22T07:26:31.704507+00:00 app[web.1]:       data: [Object]
2023-11-22T07:26:31.704507+00:00 app[web.1]:     },
2023-11-22T07:26:31.704507+00:00 app[web.1]:     req: {
2023-11-22T07:26:31.704507+00:00 app[web.1]:       url: 'https://api.ebay.com/sell/inventory/v1/inventory_item/SK-568',
2023-11-22T07:26:31.704508+00:00 app[web.1]:       method: 'put',
2023-11-22T07:26:31.704508+00:00 app[web.1]:       headers: [Object [AxiosHeaders]],
2023-11-22T07:26:31.704508+00:00 app[web.1]:       params: undefined
2023-11-22T07:26:31.704508+00:00 app[web.1]:     },
2023-11-22T07:26:31.704508+00:00 app[web.1]:     [Symbol(raw-error)]: AxiosError: Request failed with status code 500
2023-11-22T07:26:31.704508+00:00 app[web.1]:         at settle (/app/node_modules/axios/dist/node/axios.cjs:1913:12)
2023-11-22T07:26:31.704508+00:00 app[web.1]:         at Unzip.handleStreamEnd (/app/node_modules/axios/dist/node/axios.cjs:3008:11)
2023-11-22T07:26:31.704509+00:00 app[web.1]:         at Unzip.emit (node:events:527:35)
2023-11-22T07:26:31.704509+00:00 app[web.1]:         at endReadableNT (node:internal/streams/readable:1589:12)
2023-11-22T07:26:31.704509+00:00 app[web.1]:         at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
2023-11-22T07:26:31.704509+00:00 app[web.1]:       code: 'ERR_BAD_RESPONSE',
2023-11-22T07:26:31.704509+00:00 app[web.1]:       config: [Object],
2023-11-22T07:26:31.704510+00:00 app[web.1]:       request: [ClientRequest],
2023-11-22T07:26:31.704510+00:00 app[web.1]:       response: [Object]
2023-11-22T07:26:31.704510+00:00 app[web.1]:     }
2023-11-22T07:26:31.704510+00:00 app[web.1]:   }
2023-11-22T07:26:31.704510+00:00 app[web.1]: }
```

**Comment by sughramehdi-swagkicks** [comment]
trying to create an Inventory Item using the API, I am getting a 500 error. Any ideas?

**Comment by dantio** [comment]
Why are you using the custom headers? Try without it.

**Comment by sughramehdi-swagkicks** [comment]
Wow, This Worked. Thanks a lot!

**Comment by dantio** [comment]
Does this timeout happen on your server or from eBay?
Try to increase the timeout:
```js
eBay.req.instance.interceptors.request.use(config => {
  config.timeout = 5000; // Wait for 5 seconds before timing out
  return config;
});

```

**Comment by sughramehdi-swagkicks** [comment]
The server still times out. :/
My deployment is on Heroku. It times out after 30 seconds

**Comment by dantio** [comment]
I need more information. Maybe you can show me the whole code? Are you using the Sandbox Env? Are other API calls working correctly?

**Comment by sughramehdi-swagkicks** [comment]
It worked. I removed the headers.

The heroku server was timing out because there was an authorization issue.
