### ISSUE TITLE
Application Access Token

### ISSUE THREAD

**Issue by nrathi** [hendt/ebay-api#176]
Hi,

My understanding from the README is that, in the absence of a user token, and application token will be generated and set. Furthermore, the application token will be valid for GET requests: 

https://github.com/hendt/ebay-api/tree/a0076fd7171f12493db62fca6dba9ba4338ad2dd?tab=readme-ov-file#application-access-token-client-credentials-grant-flow
> If no other token is set, this token will be obtained automatically in the process of calling an RESTful API.

I'm trying this out in practice with the call `GetCategoryFeatures`:

```
    console.log("access token", await this.api.OAuth2.getAccessToken());
    return this.api.trading.GetCategoryFeatures(
      { CategoryID: categoryId, DetailLevel: "ReturnAll" },
      { useIaf: true },
    );
```

**The scope is set properly in the case of user token vs. access token.** (This is important, in case anyone else reads this.) 

The access token is defined. However, the call is failing with the following error (same error, with and without "useIaf") : 

```
[service] EbayApiError: Unknown Error.
    at checkEBayResponse (/my-app/node_modules/.pnpm/ebay-api@8.7.2-RC.0_a6zy2x3qixhdhabcw5izcodzwu/node_modules/ebay-api/lib/errors/index.js:193:15)
    at XMLRequest.request (/my-app/node_modules/.pnpm/ebay-api@8.7.2-RC.0_a6zy2x3qixhdhabcw5izcodzwu/node_modules/ebay-api/lib/api/traditional/XMLRequest.js:118:46)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Traditional.request (/my-app/node_modules/.pnpm/ebay-api@8.7.2-RC.0_a6zy2x3qixhdhabcw5izcodzwu/node_modules/ebay-api/lib/api/traditional/index.js:186:20)
    at async Object.GetCategoryFeatures (/my-app/node_modules/.pnpm/ebay-api@8.7.2-RC.0_a6zy2x3qixhdhabcw5izcodzwu/node_modules/ebay-api/lib/api/traditional/index.js:44:24)
    at async Promise.all (index 0) {
  description: 'Unknown Error.',
  meta: {
    Timestamp: '2024-07-26T00:30:29.430Z',
    Ack: 'Failure',
    Errors: {
      ShortMessage: 'Unknown Error.',
      LongMessage: 'Unknown Error.',
      ErrorCode: 17460,
      SeverityCode: 'Error',
      ErrorClassification: 'RequestError'
    },
    Version: 1367,
    Build: 'E1367_CORE_APICATALOG_19146446_R1',
    [Symbol(raw-error)]: {
      Timestamp: '2024-07-26T00:30:29.430Z',
      Ack: 'Failure',
      Errors: [Object],
      Version: 1367,
      Build: 'E1367_CORE_APICATALOG_19146446_R1'
    }
  }
}
```

Any ideas? It's my first time trying to make a GET request without creds.

**Comment by nrathi** [comment]
Nevermind, this seems to be an eBay bug: https://community.ebay.com/t5/Report-eBay-Technical-Issues/GetCategoryFeatures-is-returning-quot-UnknownError-quot-with/m-p/34590350
