### ISSUE TITLE
Having Tough Time Getting AddFixedPriceItem to list an item

### ISSUE THREAD

**Issue by doverradio** [hendt/ebay-api#31]
Hi, I am trying to use your library with ExpressJS.

Not sure if I'm even doing this right but I have set up 4 endpoints to handle the 4 parts mentioned in your README.md:

```
// Step 1: Generate OAuth URL
router.post("/ebay/getoauthurl", generateEbayOauthUrl)
```

```
// Step 2: Get eBay Code
router.post("/ebayaccepted", getEbayCode)
```

```
// Step 3: get eBay Token and save to localhost
router.post("/ebay/gettoken", getToken)
```

```
// Step 4: Add Fixed Price Item
router.post("/ebay/addfixedpriceitem", addFixedPriceItem)
```

So, in Step 1, the controller method looks like this:
```
exports.generateEbayOauthUrl = ( req, res ) => {
    eBay.auth.oAuth2.setScope([
      'https://api.ebay.com/oauth/api_scope',
      'https://api.ebay.com/oauth/api_scope/sell.fulfillment.readonly',
      'https://api.ebay.com/oauth/api_scope/sell.fulfillment'
  ]);

  const url = eBay.auth.oAuth2.generateAuthUrl();
  // 2. Open Url and Grant Access
  console.log('Open URL', url);
  res.json(url)
  
}
```
This endpoint successfully works and I get the response containing the url.
I am testing this in Postman, so when I see the url, I click it and then see in the browser the code in the url params.

After, I take that code and send it to Step 2, like so:
```
exports.getEbayCode = ( req, res ) => {
  let code = req.params.code
  const expires_in = req.params.expires_in
  res.json({code, expires_in})

}
```
But when I try to get the token, it fails.  Here is my code to handle getting the token:
```
exports.getToken = async (req, res) => {
  let code = req.body.code  // oauth granted code
  
  const token = await eBay.auth.oAuth2.getToken(code);

  let result = eBay.auth.oAuth2.setCredentials(token);
  res.json(result)

}
```
Here is what the error shows:
```
(node:20020) UnhandledPromiseRejectionWarning: Error: Request failed with status code 400
    at createError (C:\Users\Eric\Desktop\wiki\e\ebay\ebay-selling-platform\backend\node_modules\axios\lib\core\createError.js:16:15)
    at settle (C:\Users\Eric\Desktop\wiki\e\ebay\ebay-selling-platform\backend\node_modules\axios\lib\core\settle.js:17:12)
    at IncomingMessage.handleStreamEnd (C:\Users\Eric\Desktop\wiki\e\ebay\ebay-selling-platform\backend\node_modules\axios\lib\adapters\http.js:260:11)
    at IncomingMessage.emit (events.js:327:22)
    at IncomingMessage.EventEmitter.emit (domain.js:486:12)
    at endReadableNT (_stream_readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
(node:20020) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with 
.catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:20020) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

As a result, I never make it to list the AddFixedPriceItem call to try to list.

I am pretty sure I got the above steps wrong but I did not find any examples of what a successful call from beginning to end is.

Please help and give guidance so I can finally use this library to list items to ebay!  Thank you!

**Comment by dantio** [comment]
Hey,
we also use the lib with Express, it works perfectly.

Let's check the exception to examine the error:

```js
try {
 const token = await eBay.auth.oAuth2.getToken(code);

  let result = eBay.auth.oAuth2.setCredentials(token);
} catch (e) {
 console.error(e);
}
```

**Comment by doverradio** [comment]
Hello,

Thank you for your response.

I made the following change in my code:

```
exports.getToken = async (req, res) => {
  try {
  console.log(`Made it to getEbayToken!
  Here's req.body: `, req.body)
  let code = req.body.code  // oauth granted code
  console.log(`L91 code: `, code)
  
  const token = await eBay.auth.oAuth2.getToken(code);
  console.log(`L94 token: `, token)

  let result = eBay.auth.oAuth2.setCredentials(token);
  res.json(result)

  } catch(e) {
    console.log(`L104 e: `, e)
  }
}
```
However, the result became this:

```
L104 e:  Error: Request failed with status code 400
    at createError (C:\Users\Eric\Desktop\wiki\e\ebay\ebay-selling-platform\backend\node_modules\axios\lib\core\createError.js:16:15)
    at settle (C:\Users\Eric\Desktop\wiki\e\ebay\ebay-selling-platform\backend\node_modules\axios\lib\core\settle.js:17:12)
    at IncomingMessage.handleStreamEnd (C:\Users\Eric\Desktop\wiki\e\ebay\ebay-selling-platform\backend\node_modules\axios\lib\adapters\http.js:260:11)
    at IncomingMessage.emit (events.js:327:22)
    at IncomingMessage.EventEmitter.emit (domain.js:486:12)
    at endReadableNT (_stream_readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  config: {
    url: 'https://api.ebay.com/identity/v1/oauth2/token',
    method: 'post',
    data: 'grant_type=authorization_code&code=XXXXXXXXXX',
    headers: {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/x-www-form-urlencoded',
      'Access-Control-Allow-Origin': '*',
      'Access-Control-Allow-Headers': 'X-Requested-With, Origin, Content-Type, X-Auth-Token',
      'Access-Control-Allow-Methods': 'GET, PUT, POST, DELETE',
      'User-Agent': 'axios/0.21.1',
      'Content-Length': 206
    },
    auth: {
      username: 'XXXXX',
      password: 'XXXXX'
    },
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    adapter: [Function: httpAdapter],
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus]
  },
  request: <ref *1> ClientRequest {
    _events: [Object: null prototype] {
      socket: [Function (anonymous)],
      abort: [Function (anonymous)],
      aborted: [Function (anonymous)],
      connect: [Function (anonymous)],
      error: [Function (anonymous)],
      timeout: [Function (anonymous)],
      prefinish: [Function: requestOnPrefinish]
    },
    _eventsCount: 7,
    _maxListeners: undefined,
    outputData: [],
    outputSize: 0,
    writable: true,
    destroyed: false,
    _last: true,
    chunkedEncoding: false,
    shouldKeepAlive: false,
    _defaultKeepAlive: true,
    useChunkedEncodingByDefault: true,
    sendDate: false,
    _removedConnection: false,
    _removedContLen: false,
    _removedTE: false,
    _contentLength: null,
    _hasBody: true,
    _trailer: '',
    finished: true,
    _headerSent: true,
    socket: TLSSocket {
      _tlsOptions: [Object],
      _secureEstablished: true,
      _securePending: false,
      _newSessionPending: false,
      _controlReleased: true,
      secureConnecting: false,
      _SNICallback: null,
      servername: 'api.ebay.com',
      alpnProtocol: false,
      authorized: true,
      authorizationError: null,
      encrypted: true,
      _events: [Object: null prototype],
      _eventsCount: 10,
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'api.ebay.com',
      _readableState: [ReadableState],
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: undefined,
      _server: null,
      ssl: [TLSWrap],
      _requestCert: true,
      _rejectUnauthorized: true,
      parser: null,
      _httpMessage: [Circular *1],
      [Symbol(res)]: [TLSWrap],
      [Symbol(verified)]: true,
      [Symbol(pendingSession)]: null,
      [Symbol(async_id_symbol)]: 147,
      [Symbol(kHandle)]: [TLSWrap],
      [Symbol(kSetNoDelay)]: false,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(connect-options)]: [Object],
      [Symbol(RequestTimeout)]: undefined
    },
    _header: 'POST /identity/v1/oauth2/token HTTP/1.1\r\n' +
      'Accept: application/json, text/plain, */*\r\n' +
      'Content-Type: application/x-www-form-urlencoded\r\n' +
      'Access-Control-Allow-Origin: *\r\n' +
      'Access-Control-Allow-Headers: X-Requested-With, Origin, Content-Type, X-Auth-Token\r\n' +
      'Access-Control-Allow-Methods: GET, PUT, POST, DELETE\r\n' +
      'User-Agent: axios/0.21.1\r\n' +
      'Content-Length: 206\r\n' +
      'Host: api.ebay.com\r\n' +
      'Authorization: Basic XXXXX' +
      'Connection: close\r\n' +
      '\r\n',
    _keepAliveTimeout: 0,
    _onPendingData: [Function: noopPendingOutput],
    agent: Agent {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      defaultPort: 443,
      protocol: 'https:',
      options: [Object],
      requests: {},
      sockets: [Object],
      freeSockets: {},
      keepAliveMsecs: 1000,
      keepAlive: false,
      maxSockets: Infinity,
      maxFreeSockets: 256,
      scheduling: 'fifo',
      maxTotalSockets: Infinity,
      totalSocketCount: 1,
      maxCachedSessions: 100,
      _sessionCache: [Object],
      [Symbol(kCapture)]: false
    },
    socketPath: undefined,
    method: 'POST',
    maxHeaderSize: undefined,
    insecureHTTPParser: undefined,
    path: '/identity/v1/oauth2/token',
    _ended: true,
    res: IncomingMessage {
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 3,
      _maxListeners: undefined,
      socket: [TLSSocket],
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      headers: [Object],
      rawHeaders: [Array],
      trailers: {},
      rawTrailers: [],
      aborted: false,
      upgrade: false,
      url: '',
      method: null,
      statusCode: 400,
      statusMessage: 'Bad Request',
      client: [TLSSocket],
      _consuming: false,
      _dumped: false,
      req: [Circular *1],
      responseUrl: 'XXXXXXXXXXXXXXX',
      redirects: [],
      [Symbol(kCapture)]: false,
      [Symbol(RequestTimeout)]: undefined
    },
    aborted: false,
    timeoutCb: null,
    upgradeOrConnect: false,
    parser: null,
    maxHeadersCount: null,
    reusedSocket: false,
    host: 'api.ebay.com',
    protocol: 'https:',
    _redirectable: Writable {
      _writableState: [WritableState],
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      _options: [Object],
      _ended: true,
      _ending: true,
      _redirectCount: 0,
      _redirects: [],
      _requestBodyLength: 206,
      _requestBodyBuffers: [],
      _onNativeResponse: [Function (anonymous)],
      _currentRequest: [Circular *1],
      _currentUrl: 'XXXXXXXXXXXXXXX,
      [Symbol(kCapture)]: false
    },
    [Symbol(kCapture)]: false,
    [Symbol(kNeedDrain)]: false,
    [Symbol(corked)]: 0,
    [Symbol(kOutHeaders)]: [Object: null prototype] {
      accept: [Array],
      'content-type': [Array],
      'access-control-allow-origin': [Array],
      'access-control-allow-headers': [Array],
      'access-control-allow-methods': [Array],
      'user-agent': [Array],
      'content-length': [Array],
      host: [Array],
      authorization: [Array]
    }
  },
  response: {
    status: 400,
    statusText: 'Bad Request',
    headers: {
      'content-length': '128',
      date: 'Mon, 22 Feb 2021 20:08:16 GMT',
      nncoection: 'close',
      rlogid: 't6ldssk67%3D9whhldssk67*%3Bhwpm%28rbpv6702-177cb5b55bc-0x12b',
      'set-cookie': [Array],
      'x-content-type-options': 'nosniff',
      'x-ebay-c-version': '1.0.0',
      'x-ebay-client-tls-version': '771, 67.49.106.73',
      'x-ebay-esb-upstream': 'oauth31.vip.ebay.com',
      'x-frame-options': 'SAMEORIGIN',
      'x-xss-protection': '1; mode=block',
      'content-type': 'application/json',
      connection: 'keep-alive',
      'strict-transport-security': 'max-age=31536000'
    },
    config: {
      url: 'https://api.ebay.com/identity/v1/oauth2/token',
      method: 'post',
      data: 'grant_type=authorization_code&code=XXXXXXXXXX',
      headers: [Object],
      auth: [Object],
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 0,
      adapter: [Function: httpAdapter],
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      maxBodyLength: -1,
      validateStatus: [Function: validateStatus]
    },
    request: <ref *1> ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: null,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      socket: [TLSSocket],
      _header: 'POST /identity/v1/oauth2/token HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'Content-Type: application/x-www-form-urlencoded\r\n' +
        'Access-Control-Allow-Origin: *\r\n' +
        'Access-Control-Allow-Headers: X-Requested-With, Origin, Content-Type, X-Auth-Token\r\n' +
        'Access-Control-Allow-Methods: GET, PUT, POST, DELETE\r\n' +
        'User-Agent: axios/0.21.1\r\n' +
        'Content-Length: 206\r\n' +
        'Host: api.ebay.com\r\n' +
        'Authorization: Basic XXXXX' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/identity/v1/oauth2/token',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'api.ebay.com',
      protocol: 'https:',
      _redirectable: [Writable],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    data: {
      error: 'invalid_grant',
      error_description: 'the provided authorization grant code is invalid or was issued to another client'
    }
  },
  isAxiosError: true,
  toJSON: [Function: toJSON]
}
```

What am I doing wrong?  

How would you do it correctly or different from how I approached this? 

I have thousands of items pending listing, hoping to use your library.

**Comment by dantio** [comment]
So the error is clear:
> error_description: 'the provided authorization grant code is invalid or was issued to another client'

Maybe something is wrong with the code? Not decoded?

**Comment by doverradio** [comment]
Ah ok I have the ruName in my ebay developer account pointing to another domain name but I am running this in localhost so I can see why this could be.  How would you do this on a development server when you're on localhost?  Ngrok?  I may have to go that way I suppose before moving this to the domain name mentioned in redirect settings in the dev account.

**Comment by dantio** [comment]
Ok, so if you get redirected to the success page and the token is used, than it won't work again...

What we do:
In generateAuthUrl() you can pass also a "state" parameter. 
So, we if the state is e.g. "dev", stop processing and redirect to localhost with the code parameter.

But please try out Ngrok and let me know if this works for you :)

**Comment by dantio** [comment]
Check if Auth'N Auth is something for you. It works only for old API but it's easier to use...

**Comment by doverradio** [comment]
Thanks to your help I was able to see the error and implemented ngrok to obtain the https url that ultimately finally produced the authorization code grant.  Now I am attempting to use that to list an item and will circle back here and let you know how it goes.  Excited!

**Comment by doverradio** [comment]
Ok I tried making the call with the auth token granted but got this error and the item did not list.  Since I am using Postman, I just copied the auth token from a prior call, then hardcoded it in a tempToken and tried running eBay.trading.AddFixedPriceItem.

Can you spot the error?  Also, not sure this is the correct syntax for the item body but I am basing that off of this [xml sample](https://github.com/bhushankumarl/eBay-node-client/blob/master/examples/javaScript/trading/sample.xml).

Here is my code to do that call:

```
exports.testListItem = (req, res) => {
  let tempToken = `XXXXX`
  eBay.auth.oAuth2.setCredentials(tempToken);

  eBay.trading.AddFixedPriceItem({
    Item: {
      Title: `Harry Potter and the Philosopher's Stone`,
      Description: {
        __cdata: '<div>This is the first book in the Harry Potter series. In excellent condition!</div>'
      },
      PrimaryCategory: {
        CategoryID: "377"
      },
      StartPrice: 1.0,
      CategoryMappingAllowed: true,
      Country: "US",
      Currency: "USD",
      ConditionID: 1000,
      DispatchTimeMax: 3,
      ListingDuration: "Days_7",
      ListingType: "Chinese",
      PaymentMethods: "PayPal",
      PayPalEmailAddress: "wikiwick151@gmail.com",
      PictureDetails: {
        PictureURL: "https://mypicserver.com/myphoto.jpg"
      },
      PostalCode: "95125",
      Quantity: "1",
      ReturnPolicy: {        
        ReturnsAcceptedOption: "ReturnsAccepted",
        RefundOption: "MoneyBack",
        ReturnsWithinOption: "Days_30",
        ShippingCostPaidByOption: "Buyer"
      },
      ShippingDetails: {
        ShippingType: "Flat",
        ShippingServiceOptions: {
          ShippingServicePriority: "1",
          ShippingService: "USPSMedia",
          ShippingServiceCost: 2.50,
        }
      },
      ShippingDetails: {
        Site: "US",
      }
    }
  })

  res.json({message:`Check if listed item`})
}
```

Here is the error I got:

```
POST /api/ebay/testlistitem 200 28.784 ms - 34
(node:17280) UnhandledPromiseRejectionWarning: EBayTokenRequired
    at EBayTokenRequired.EBayError [as constructor] (C:\Users\Eric\Desktop\wiki\e\ebay\ebay-selling-platform\backend\node_modules\@hendt\ebay-api\lib\errors\index.js:26:47)   
    at EBayTokenRequired.EbayApiError [as constructor] (C:\Users\Eric\Desktop\wiki\e\ebay\ebay-selling-platform\backend\node_modules\@hendt\ebay-api\lib\errors\index.js:101:24)
    at new EBayTokenRequired (C:\Users\Eric\Desktop\wiki\e\ebay\ebay-selling-platform\backend\node_modules\@hendt\ebay-api\lib\errors\index.js:154:23)
    at XMLRequest.handleEBayJsonError (C:\Users\Eric\Desktop\wiki\e\ebay\ebay-selling-platform\backend\node_modules\@hendt\ebay-api\lib\api\traditional\XMLRequest.js:209:27)  
    at XMLRequest.<anonymous> (C:\Users\Eric\Desktop\wiki\e\ebay\ebay-selling-platform\backend\node_modules\@hendt\ebay-api\lib\api\traditional\XMLRequest.js:188:30)
    at step (C:\Users\Eric\Desktop\wiki\e\ebay\ebay-selling-platform\backend\node_modules\@hendt\ebay-api\lib\api\traditional\XMLRequest.js:44:23)
    at Object.next (C:\Users\Eric\Desktop\wiki\e\ebay\ebay-selling-platform\backend\node_modules\@hendt\ebay-api\lib\api\traditional\XMLRequest.js:25:53)
    at fulfilled (C:\Users\Eric\Desktop\wiki\e\ebay\ebay-selling-platform\backend\node_modules\@hendt\ebay-api\lib\api\traditional\XMLRequest.js:16:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:17280) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:17280) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by dantio** [comment]
You have to use try catch to avoid unhandled exception and see what the real cause is.

**Comment by doverradio** [comment]
Ok, put try/catch like so:

```
exports.testListItem = (req, res) => {
  console.log(`Made it to testListItem!  Here is req.body: `, req.body)
  let token = req.body.access_token
  eBay.auth.oAuth2.setCredentials(token);

  try {
  eBay.trading.AddFixedPriceItem({
    RequesterCredentials: {
      eBayAuthToken: token
    },
    Item: {
      Title: `Harry Potter and the Philosopher's Stone`,
      Description: {
        __cdata: '<div>This is the first book in the Harry Potter series. In excellent condition!</div>'
      },
      PrimaryCategory: {
        CategoryID: "377"
      },
      StartPrice: 1.0,
      CategoryMappingAllowed: true,
      Country: "US",
      Currency: "USD",
      ConditionID: 1000,
      DispatchTimeMax: 3,
      ListingDuration: "GTC",
      ListingType: "FixedPriceItem",
      PaymentMethods: "PayPal",
      PayPalEmailAddress: "xxxxx",
      PictureDetails: {
        PictureURL: "https://mypicserver.com/myphoto.jpg"
      },
      PostalCode: "95125",
      Quantity: "1",
      ReturnPolicy: {        
        ReturnsAcceptedOption: "ReturnsAccepted",
        RefundOption: "MoneyBack",
        ReturnsWithinOption: "Days_30",
        ShippingCostPaidByOption: "Buyer"
      },
      ShippingDetails: {
        ShippingType: "Flat",
        ShippingServiceOptions: {
          ShippingServicePriority: "1",
          ShippingService: "USPSMedia",
          ShippingServiceCost: 2.50,
        }
      },
      ShippingDetails: {
        Site: "US",
      }
    }
  })

  res.json({message:`Check if listed item`})
  } 
  catch(e) {
    res.json({error: e})
  }


}
```

But got this error:
```
(node:10780) UnhandledPromiseRejectionWarning: EbayApiError
    at EbayApiError.EBayError [as constructor] (C:\Users\Eric\Desktop\wiki\e\ebay\ebay-selling-platform\backend\node_modules\@hendt\ebay-api\lib\errors\index.js:26:47)        
    at new EbayApiError (C:\Users\Eric\Desktop\wiki\e\ebay\ebay-selling-platform\backend\node_modules\@hendt\ebay-api\lib\errors\index.js:101:24)
    at XMLRequest.handleEBayJsonError (C:\Users\Eric\Desktop\wiki\e\ebay\ebay-selling-platform\backend\node_modules\@hendt\ebay-api\lib\api\traditional\XMLRequest.js:211:19)  
    at XMLRequest.<anonymous> (C:\Users\Eric\Desktop\wiki\e\ebay\ebay-selling-platform\backend\node_modules\@hendt\ebay-api\lib\api\traditional\XMLRequest.js:188:30)
    at step (C:\Users\Eric\Desktop\wiki\e\ebay\ebay-selling-platform\backend\node_modules\@hendt\ebay-api\lib\api\traditional\XMLRequest.js:44:23)
    at Object.next (C:\Users\Eric\Desktop\wiki\e\ebay\ebay-selling-platform\backend\node_modules\@hendt\ebay-api\lib\api\traditional\XMLRequest.js:25:53)
    at fulfilled (C:\Users\Eric\Desktop\wiki\e\ebay\ebay-selling-platform\backend\node_modules\@hendt\ebay-api\lib\api\traditional\XMLRequest.js:16:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:10780) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:10780) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Perhaps the item content I am sending is not right?  I am so close to listing this item!

**Comment by doverradio** [comment]
After viewing the error (finally got the error to show, thank you for try/catch suggestion) I got this:
```
{
    "error": {
        "meta": [
            {
                "ShortMessage": "Seller Profiles will soon be mandatory while creating a new listing for business policies opted in sellers.",
                "LongMessage": "Seller Profiles will soon be mandatory while creating a new listing. Support for Legacy Shipping, Payment and Returns fields will be going away for business policies opted in sellers.",
                "ErrorCode": 21919456,
                "SeverityCode": "Warning",
                "ErrorClassification": "RequestError"
            },
            {
                "ShortMessage": "PayPal not applicable for managed payments.",
                "LongMessage": "This selling account is enabled for payments managed by eBay. PayPal is not currently accepted as a payment method and has been removed from the listing.",
                "ErrorCode": 21920208,
                "SeverityCode": "Warning",
                "ErrorParameters": {
                    "Value": "PayPal"
                },
                "ErrorClassification": "RequestError"
            },
            {
                "ShortMessage": "A shipping service is not specified.",
                "LongMessage": "At least one valid shipping service must be specified.",
                "ErrorCode": 21915469,
                "SeverityCode": "Error",
                "ErrorClassification": "RequestError"
            }
        ],
        "name": "EbayApiError"
    }
}
```

So I know I'm on the right track.

**Comment by doverradio** [comment]
Sorry to keep on this but I still have not been able to list.  

Here is my current code:
```
exports.testListItem = async (req, res) => {
  console.log(`L115 Made it to testListItem!  Here is req.body: `, req.body)
  let token = req.body.access_token
  eBay.auth.oAuth2.setCredentials(token);

  try {
  await eBay.trading.AddFixedPriceItem({
    RequesterCredentials: {
      eBayAuthToken: token
    },
    Item: {
      Title: `Harry Potter and the Philosopher's Stone`,
      Description: {
        __cdata: '<div>This is the first book in the Harry Potter series. In excellent condition!</div>'
      },
      PrimaryCategory: {
        CategoryID: "377"
      },
      StartPrice: 1.0,
      CategoryMappingAllowed: true,
      Country: "US",
      Currency: "USD",
      ConditionID: 1000,
      DispatchTimeMax: 3,
      ListingDuration: "GTC",
      ListingType: "FixedPriceItem",
      // PaymentMethods: "PayPal",
      // PayPalEmailAddress: "",
      PictureDetails: {
        PictureURL: "https://mypicserver.com/myphoto.jpg"
      },
      PostalCode: "95125",
      Quantity: "1",
      ReturnPolicy: {        
        ReturnsAcceptedOption: "ReturnsAccepted",
        RefundOption: "MoneyBack",
        ReturnsWithinOption: "Days_30",
        ShippingCostPaidByOption: "Buyer"
      },
      SellerShippingProfile: {
        ShippingProfileID: "200685821019"
      },
      SellerReturnProfile: {
        ReturnProfileID: "200685819019"
      },
      SellerPaymentProfile: {
        PaymentProfileID: "200685820019"
      },
      ShippingDetails: {
        ShippingType: "Flat",
        ShippingServiceOptions: {
          ShippingServicePriority: "1",
          ShippingService: "USPS",
          ShippingServiceCost: 2.50,
        }
      },
      ShippingDetails: {
        Site: "US",
      }
    }
  })

  res.json({message:`Check if listed item`})
  } 
  catch(e) {
    console.log(`Got error: `, e)
    res.json({error: e})
  }
}
```

Here is the error I get:
```
{
    "error": {
        "meta": [
            {
                "ShortMessage": "Seller Profiles will soon be mandatory while creating a new listing for business policies opted in sellers.",
                "LongMessage": "Seller Profiles will soon be mandatory while creating a new listing. Support for Legacy Shipping, Payment and Returns fields will be going away for business policies opted in sellers.",
                "ErrorCode": 21919456,
                "SeverityCode": "Warning",
                "ErrorClassification": "RequestError"
            },
            {
                "ShortMessage": "A shipping service is not specified.",
                "LongMessage": "At least one valid shipping service must be specified.",
                "ErrorCode": 21915469,
                "SeverityCode": "Error",
                "ErrorClassification": "RequestError"
            }
        ],
        "name": "EbayApiError"
    }
}
```

I tried retrieving the business policies IDs for SellerShippingProfile, SellerReturnProfile, and SellerPaymentProfile by logging into my ebay account, then going to https://www.bizpolicy.ebay.com/businesspolicy/manage#topOfMain, then clicking directly on each listed named policies of Payment, Return, and Shipping, then put them in my code but it's acting like it's not considering those.  How were you able to get past this part?

**Comment by doverradio** [comment]
Nevermind the above, I GOT IT TO LIST AN ITEM!!! WOOOO!!! 

For future reference, here is what successfully worked for me:

```
exports.testListItem = async (req, res) => {
  console.log(`L115 Made it to testListItem!  Here is req.body: `, req.body)
  let token = req.body.access_token
  eBay.auth.oAuth2.setCredentials(token);

  try {
  await eBay.trading.AddFixedPriceItem({
    RequesterCredentials: {
      eBayAuthToken: token
    },
    Item: {
      Title: `Harry Potter and the Philosopher's Stone`,
      Description: {
        __cdata: '<div>This is the first book in the Harry Potter series. In excellent condition!</div>'
      },
      PrimaryCategory: {
        CategoryID: "377"
      },
      StartPrice: 1.0,
      CategoryMappingAllowed: true,
      Country: "US",
      Currency: "USD",
      ConditionID: 1000,
      DispatchTimeMax: 3,
      ListingDuration: "GTC",
      ListingType: "FixedPriceItem",
      PictureDetails: {
        PictureURL: "https://mypicserver.com/myphoto.jpg"
      },
      PostalCode: "95125",
      Quantity: "1",
      SellerProfiles: {
        SellerShippingProfile: {
          ShippingProfileID: "73548869019",
          ShippingProfileName: "ssgShipping"
        },
        SellerReturnProfile: {
          ReturnProfileID: "92162434019",
          ReturnProfileName: "ssgReturns"
        },
        SellerPaymentProfile: {
          PaymentProfileID: "57417135019",
          PaymentProfileName: "ssgPayments"
        },
      },
    }
  })

  res.json({message:`Check if listed item`})
  } 
  catch(e) {
    console.log(`Got error: `, e)
    res.json({error: e})
  }
}
```

SO HAPPY RIGHT NOW YOU HAVE NO IDEA!  SO LONG THIS ELUDED ME.
