### ISSUE TITLE
Having difficulty with getting a new access token from calling refreshToken()

### ISSUE THREAD

**Issue by doverradio** [hendt/ebay-api#53]
Hi, I am receiving undefined for the result of the token after calling refreshToken.  How do you make the refresh call correctly?

Please see my code below.  This is a controller method of Express and I am using mongoose and there is a User model in there.

```
exports.getItem = async (req, res) => {

  let { ebayItemId, user } = req.body // user is _id
  let result, token
  
  let { access_token } = await User.findById({_id: user}) // retrieve user and refresh tokens
  console.log(`access_token: `, access_token)

  eBay.auth.oAuth2.setCredentials(access_token);   // Get access token and pass it to this method

  try{ // make the call (which is expected to fail in order to activate the refresh token...)
    result = await eBay.browse.getItem(`v1|${ebayItemId}|0`)
  } catch (e) {
    console.log(`What's the problem #1...`, e)
  }
  
  try { // trying to get the refresh token
    token = await eBay.auth.oAuth2.refreshToken()
    token = await token.json()
    console.log(`New refreshed token? Check this: `, token)
  } catch (e) { // left out the error because it's enormous and contains the full request...
    console.log(`Token got a problem...`)
  }
  
  try {
    eBay.auth.oAuth2.setCredentials(token);
    result = await eBay.browse.getItem(`v1|${ebayItemId}|0`)
    result = await result.json()

  } catch (e) {
    console.log(`What's the problem #3...`, e)
  }

  console.log(`Final result: `, result)
  res.json(result)
}
```
The output I get is this...
```
What's the problem #1... TypeError: Cannot read property 'getItem' of undefined
    at exports.getItem (C:\Users\User\project_root\controllers\ebay.js:470:34)
    at process._tickCallback (internal/process/next_tick.js:68:7)
What's the problem #2
What's the problem #3... TypeError: Cannot read property 'getItem' of undefined
    at exports.getItem (C:\Users\User\project_root\controllers\ebay.js:490:34)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Final result:  undefined

```

What is the correct way to obtain a new token from calling refreshToken?

I had saved both the access_token and refresh_token in the database from the initial authorization.

Days later, I wanted to test if this code worked as I knew it would be a hard expired access_token.

**Comment by dantio** [comment]
It's `eBay.buy.browse.getItem()`, you missed `buy`.

The token is refreshed automatically if the `refresh_token` is also set. Instead of storing the `access_token` you have to store the WHOLE token that looks like this:
```js
{
      access_token: 'accessToken',
      refresh_token_expires_in: 0,
      refresh_token: 'refresh_token', // this is required to refresh the token
      token_type: 'token_type',
      expires_in: 7200
    }
```

Why are you calling `result.json()`? The result is already in Json.

Actually you don't even need the Access Token for getItem. Checkout the example here https://hendt.github.io/ebay-api/ maybe it will help you.

**Comment by doverradio** [comment]
Ok and where does the `refresh_token` get set?  During the literal first authorization call?

**Comment by dantio** [comment]
Exactly. `const token = await eBay.àuth.oAuth2.getToken(code);` will return the whole token and you need to store it.
Than you can use something like 
```js
let { token } = await User.findById({_id: user});
eBay.auth.oAuth2.setCredentials(access_token);
```

**Comment by doverradio** [comment]
Do you mean like this?

```
let { token } = await User.findById({_id: user})
let { access_token } = token
eBay.auth.oAuth2.setCredentials(access_token)

```

**Comment by dantio** [comment]
My bad, I fixed my code should be `eBay.auth.oAuth2.setCredentials(token);`
