### ISSUE TITLE
Error [EbayApiError]: IAF token supplied is invalid. / 'invalid_grant' / 'the provided authorization refresh token is invalid or was issued to another client'

### ISSUE THREAD

**Issue by doverradio** [hendt/ebay-api#77]
Hi, I have been successfully listing items to ebay on behalf of members of my site.

A problem has been happening for the past several days when it comes time to reprice/end their listings (on their behalf) and I attempt to relist items.  I am receiving this error:
```
Got error:  Error [EbayApiError]: IAF token supplied is invalid.
    at EbayApiError.EBayError [as constructor] (/root/myserver/node_modules/@hendt/ebay-api/lib/errors/index.js:26:47)
    at new EbayApiError (/root/myserver/node_modules/@hendt/ebay-api/lib/errors/index.js:101:24)
    at XMLRequest.handleEBayJsonError (/root/myserver/node_modules/@hendt/ebay-api/lib/api/traditional/XMLRequest.js:270:19)
    at XMLRequest.<anonymous> (/root/myserver/node_modules/@hendt/ebay-api/lib/api/traditional/XMLRequest.js:247:30)
    at step (/root/myserver/node_modules/@hendt/ebay-api/lib/api/traditional/XMLRequest.js:63:23)
    at Object.next (/root/myserver/node_modules/@hendt/ebay-api/lib/api/traditional/XMLRequest.js:44:53)
    at fulfilled (/root/myserver/node_modules/@hendt/ebay-api/lib/api/traditional/XMLRequest.js:35:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  meta: {
    ShortMessage: 'Invalid IAF token.',
    LongMessage: 'IAF token supplied is invalid.',
    ErrorCode: 21916984,
    SeverityCode: 'Error',
    ErrorClassification: 'RequestError'
  }
}
```

What could be the cause of this error?  

I believe I am correctly generating User access tokens because they do succeed in listing the items initially.

However, the next day comes and my system tries to revise their listings (change price or end listing) and it throws the error that the `IAF token supplied is invalid`.  

Here is my code that attempts to refresh the token below.  Is it that I am generating the WRONG token every time??
```
exports.refreshEbayToken = async (user, eBay) => {  
    console.log(`Made it to refreshEbayToken with user...${user}`)
    let token
    let minutes
    // first check the age of the prior token

    try {
        let userData = await User.findById( {_id: user} ) // gets the user doc
        let { token_last_refresh } = userData // gets the last time the token was refreshed
        token = userData.token // assigns token from user doc to token variable
        let startDate = Date.parse(token_last_refresh) // gets last refreshed date/time
        let endDate = new Date() // creates new time as a reference point
        endDate = Date.parse(endDate) // makes it readable for next step
        let seconds = (endDate - startDate) / 1000; // get seconds
        minutes = seconds / 60; // get minutes
        console.log(`minutes since ebay token last refresh: `, minutes)
    } catch(e) { console.log(e) }
  
    if(minutes > 115) { // if 2 hours has not yet passed from minting a new one...
        try{
            token = await eBay.oAuth2.refreshClientToken() // gets the brand new application access token
            console.log(`Got the refresh token...`)
            try { // try to update the user doc with new token
                let userData = await User.findByIdAndUpdate(
                    {_id: user},
                    {$set: {
                        token: [token],
                        access_token: token.access_token,
                        token_last_refresh: Date.now()
                    }}
                    )
                token = userData.token // double confirm it's the right token by returning the overwritten doc token
                return token // send back token
            } catch(e) { console.log(e) }
        
          } catch(e) { console.log(e); return e }

    } else { // less than 2 hours since minting access token, return current token
        console.log(`Less than 2 hours since minting access token, sending current token instead...`)
        return token // send back token
    }
  }
```

Also, after noticing [this page in your code](https://github.com/hendt/ebay-api/blob/263a1c307cfa3c47214f24d50831d8f28dc3c80b/src/auth/oAuth2.ts#L242), I switched my code from `refreshClientToken` to `refreshToken` but still I got that IAF error...
```
token = await eBay.oAuth2.refreshToken()
```

Please help me.  I need to be able to reliably call ReviseFixedPriceItem as I am getting more members but everything is stopped due to this error.

Update: After refactoring my code again (thinking surely this time it will work) I got the following error (sorry it's the full error):

```
Error: Request failed with status code 400
    at createError (/root/project_directory/backend/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/root/project_directory/backend/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/root/project_directory/backend/node_modules/axios/lib/adapters/http.js:260:11)
    at IncomingMessage.emit (events.js:326:22)
    at IncomingMessage.EventEmitter.emit (domain.js:483:12)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  config: {
    url: 'https://api.ebay.com/identity/v1/oauth2/token',
    method: 'post',
    data: 'grant_type=refresh_token&scope=https%3A%2F%2Fapi.ebay.com%2Foauth%2Fapi_scope%20https%3A%2F%2Fapi.ebay.com%2Foauth%2Fapi_scope%2Fsell.fulfillment.readonly%20https%3A%2F%2Fapi.ebay.com%2Foauth%2Fapi_scope%2Fsell.fulfillment%20https%3A%2F%2Fapi.ebay.com%2Foauth%2Fapi_scope%2Fsell.account%20https%3A%2F%2Fapi.ebay.com%2Foauth%2Fapi_scope%2Fsell.account.readonly%20https%3A%2F%2Fapi.ebay.com%2Foauth%2Fapi_scope%2Fsell.inventory.readonly%20https%3A%2F%2Fapi.ebay.com%2Foauth%2Fapi_scope%2Fsell.inventory',
    headers: {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/x-www-form-urlencoded',
      'Access-Control-Allow-Origin': '*',
      'Access-Control-Allow-Headers': 'X-Requested-With, Origin, Content-Type, X-Auth-Token',
      'Access-Control-Allow-Methods': 'GET, PUT, POST, DELETE',
      'User-Agent': 'axios/0.21.1',
      'Content-Length': 500
    },
    auth: {
      username: '<removed>',
      password: '<removed>'
    },
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    adapter: [Function: httpAdapter],
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus]
  },
  request: ClientRequest {
    _events: [Object: null prototype] {
      socket: [Function],
      abort: [Function],
      aborted: [Function],
      connect: [Function],
      error: [Function],
      timeout: [Function],
      prefinish: [Function: requestOnPrefinish]
    },
    _eventsCount: 7,
    _maxListeners: undefined,
    outputData: [],
    outputSize: 0,
    writable: true,
    _last: true,
    chunkedEncoding: false,
    shouldKeepAlive: false,
    _defaultKeepAlive: true,
    useChunkedEncodingByDefault: true,
    sendDate: false,
    _removedConnection: false,
    _removedContLen: false,
    _removedTE: false,
    _contentLength: null,
    _hasBody: true,
    _trailer: '',
    finished: true,
    _headerSent: true,
    socket: TLSSocket {
      _tlsOptions: [Object],
      _secureEstablished: true,
      _securePending: false,
      _newSessionPending: false,
      _controlReleased: true,
      secureConnecting: false,
      _SNICallback: null,
      servername: 'api.ebay.com',
      alpnProtocol: false,
      authorized: true,
      authorizationError: null,
      encrypted: true,
      _events: [Object: null prototype],
      _eventsCount: 10,
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'api.ebay.com',
      _readableState: [ReadableState],
      readable: true,
      _maxListeners: undefined,
      _writableState: [WritableState],
      writable: false,
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: undefined,
      _server: null,
      ssl: [TLSWrap],
      _requestCert: true,
      _rejectUnauthorized: true,
      parser: null,
      _httpMessage: [Circular],
      [Symbol(res)]: [TLSWrap],
      [Symbol(verified)]: true,
      [Symbol(pendingSession)]: null,
      [Symbol(asyncId)]: 16460,
      [Symbol(kHandle)]: [TLSWrap],
      [Symbol(kSetNoDelay)]: false,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(connect-options)]: [Object]
    },
    connection: TLSSocket {
      _tlsOptions: [Object],
      _secureEstablished: true,
      _securePending: false,
      _newSessionPending: false,
      _controlReleased: true,
      secureConnecting: false,
      _SNICallback: null,
      servername: 'api.ebay.com',
      alpnProtocol: false,
      authorized: true,
      authorizationError: null,
      encrypted: true,
      _events: [Object: null prototype],
      _eventsCount: 10,
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'api.ebay.com',
      _readableState: [ReadableState],
      readable: true,
      _maxListeners: undefined,
      _writableState: [WritableState],
      writable: false,
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: undefined,
      _server: null,
      ssl: [TLSWrap],
      _requestCert: true,
      _rejectUnauthorized: true,
      parser: null,
      _httpMessage: [Circular],
      [Symbol(res)]: [TLSWrap],
      [Symbol(verified)]: true,
      [Symbol(pendingSession)]: null,
      [Symbol(asyncId)]: 16460,
      [Symbol(kHandle)]: [TLSWrap],
      [Symbol(kSetNoDelay)]: false,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(connect-options)]: [Object]
    },
    _header: 'POST /identity/v1/oauth2/token HTTP/1.1\r\n' +
      'Accept: application/json, text/plain, */*\r\n' +
      'Content-Type: application/x-www-form-urlencoded\r\n' +
      'Access-Control-Allow-Origin: *\r\n' +
      'Access-Control-Allow-Headers: X-Requested-With, Origin, Content-Type, X-Auth-Token\r\n' +
      'Access-Control-Allow-Methods: GET, PUT, POST, DELETE\r\n' +
      'User-Agent: axios/0.21.1\r\n' +
      'Content-Length: 500\r\n' +
      'Host: api.ebay.com\r\n' +
      'Authorization: Basic <removed>==\r\n' +
      'Connection: close\r\n' +
      '\r\n',
    _keepAliveTimeout: 0,
    _onPendingData: [Function: noopPendingOutput],
    agent: Agent {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      defaultPort: 443,
      protocol: 'https:',
      options: [Object],
      requests: {},
      sockets: [Object],
      freeSockets: {},
      keepAliveMsecs: 1000,
      keepAlive: false,
      maxSockets: Infinity,
      maxFreeSockets: 256,
      maxTotalSockets: Infinity,
      totalSocketCount: 1,
      scheduling: 'fifo',
      maxCachedSessions: 100,
      _sessionCache: [Object],
      [Symbol(kCapture)]: false
    },
    socketPath: undefined,
    method: 'POST',
    insecureHTTPParser: undefined,
    path: '/identity/v1/oauth2/token',
    _ended: true,
    res: IncomingMessage {
      _readableState: [ReadableState],
      readable: false,
      _events: [Object: null prototype],
      _eventsCount: 3,
      _maxListeners: undefined,
      socket: [TLSSocket],
      connection: [TLSSocket],
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      headers: [Object],
      rawHeaders: [Array],
      trailers: {},
      rawTrailers: [],
      aborted: false,
      upgrade: false,
      url: '',
      method: null,
      statusCode: 400,
      statusMessage: 'Bad Request',
      client: [TLSSocket],
      _consuming: false,
      _dumped: false,
      req: [Circular],
      responseUrl: 'https://<removed>:<removed>@api.ebay.com/identity/v1/oauth2/token',
      redirects: [],
      [Symbol(kCapture)]: false
    },
    aborted: false,
    timeoutCb: null,
    upgradeOrConnect: false,
    parser: null,
    maxHeadersCount: null,
    reusedSocket: false,
    host: 'api.ebay.com',
    protocol: 'https:',
    _redirectable: Writable {
      _writableState: [WritableState],
      writable: true,
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      _options: [Object],
      _ended: true,
      _ending: true,
      _redirectCount: 0,
      _redirects: [],
      _requestBodyLength: 500,
      _requestBodyBuffers: [],
      _onNativeResponse: [Function],
      _currentRequest: [Circular],
      _currentUrl: 'https://<removed>:<removed>@api.ebay.com/identity/v1/oauth2/token',
      [Symbol(kCapture)]: false
    },
    [Symbol(kCapture)]: false,
    [Symbol(kNeedDrain)]: false,
    [Symbol(corked)]: 0,
    [Symbol(kOutHeaders)]: [Object: null prototype] {
      accept: [Array],
      'content-type': [Array],
      'access-control-allow-origin': [Array],
      'access-control-allow-headers': [Array],
      'access-control-allow-methods': [Array],
      'user-agent': [Array],
      'content-length': [Array],
      host: [Array],
      authorization: [Array]
    }
  },
  response: {
    status: 400,
    statusText: 'Bad Request',
    headers: {
      rlogid: '<removed>',
      'x-ebay-c-version': '1.0.0',
      'x-ebay-client-tls-version': 'TLSv1.3',
      'x-frame-options': 'SAMEORIGIN',
      'x-content-type-options': 'nosniff',
      'x-xss-protection': '1; mode=block',
      'set-cookie': [Array],
      'content-type': 'application/json',
      'content-length': '131',
      date: 'Mon, 07 Jun 2021 23:45:59 GMT',
      server: 'ebay-proxy-server',
      'x-envoy-upstream-service-time': '38',
      'x-ebay-pop-id': 'UFES2-RNOAZ03-api',
      connection: 'close'
    },
    config: {
      url: 'https://api.ebay.com/identity/v1/oauth2/token',
      method: 'post',
      data: 'grant_type=refresh_token&scope=https%3A%2F%2Fapi.ebay.com%2Foauth%2Fapi_scope%20https%3A%2F%2Fapi.ebay.com%2Foauth%2Fapi_scope%2Fsell.fulfillment.readonly%20https%3A%2F%2Fapi.ebay.com%2Foauth%2Fapi_scope%2Fsell.fulfillment%20https%3A%2F%2Fapi.ebay.com%2Foauth%2Fapi_scope%2Fsell.account%20https%3A%2F%2Fapi.ebay.com%2Foauth%2Fapi_scope%2Fsell.account.readonly%20https%3A%2F%2Fapi.ebay.com%2Foauth%2Fapi_scope%2Fsell.inventory.readonly%20https%3A%2F%2Fapi.ebay.com%2Foauth%2Fapi_scope%2Fsell.inventory',
      headers: [Object],
      auth: [Object],
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 0,
      adapter: [Function: httpAdapter],
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      maxBodyLength: -1,
      validateStatus: [Function: validateStatus]
    },
    request: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: null,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      socket: [TLSSocket],
      connection: [TLSSocket],
      _header: 'POST /identity/v1/oauth2/token HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'Content-Type: application/x-www-form-urlencoded\r\n' +
        'Access-Control-Allow-Origin: *\r\n' +
        'Access-Control-Allow-Headers: X-Requested-With, Origin, Content-Type, X-Auth-Token\r\n' +
        'Access-Control-Allow-Methods: GET, PUT, POST, DELETE\r\n' +
        'User-Agent: axios/0.21.1\r\n' +
        'Content-Length: 500\r\n' +
        'Host: api.ebay.com\r\n' +
        'Authorization: Basic <removed>==\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      insecureHTTPParser: undefined,
      path: '/identity/v1/oauth2/token',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'api.ebay.com',
      protocol: 'https:',
      _redirectable: [Writable],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    data: {
      error: 'invalid_grant',
      error_description: 'the provided authorization refresh token is invalid or was issued to another client'
    }
  },
  isAxiosError: true,
  toJSON: [Function: toJSON]
}


```

**Comment by doverradio** [comment]
Welp, found out that it was due to my own mistake in pulling the token from the database I had to do token[0] so it was instead trying to read an array instead of the token object.
